### ISSUE TITLE
Add the app into F-Droid

### ISSUE THREAD

**Issue by KOLANICH** [Mishiranu/Dashchan#105]

**Comment by kisleey** [comment]
Well, there is ~70 modules. Do you think it's good idea to upload all of them to F-Droid?

**Comment by Mishiranu** [comment]
I don't think it is possible with Dashchan modular system. Dashchan also has its own updater.

I don't sure Dashchan is acceptable for F-Droid, because it can be linked with non-free modules.

**Comment by KOLANICH** [comment]
>Well, there is ~70 modules. Do you think it's good idea to upload all of them to F-Droid?

Of course I do. There are apps in F-Droid doing this.

**Comment by jiyagaimo** [comment]
@Mishiranu There are plenty of apps with modular systems in F-Droid. [1] I'm pretty sure that they will accept it if the auto updater can easily be removed from the code before compilation.

[1]
https://f-droid.org/repository/browse/?fdfilter=AnySoftKeyboard
https://f-droid.org/repository/browse/?fdfilter=MAXS

**Comment by KOLANICH** [comment]
Even if they won't accept, you can always create own repo compatible with fdroid client

**Comment by Mishiranu** [comment]
@jiyagaimo that's good, but I don't think it will be easy to upload each new extension for me. As I know, developers make requests on forum, so I have to make request for each extension. That's annoying.

@KOLANICH yes, I thought about it. But in this case F-Droid loses its sense. F-Droid assures that packages are built from source code, but own repos will contain the same binaries as on my github repos.

**Comment by KOLANICH** [comment]
>@KOLANICH yes, I thought about it. But in this case F-Droid loses its
>sense. F-Droid assures that packages are built from source code, but
>own repos will contain the same binaries as on my github repos.

Some profit remains: I will be able to install it through package manager. BTW, f-droid should be most profitable if a dev has own build server with reproducible builds. Than fdroid should preserve dev's original signature.

**Comment by jiyagaimo** [comment]
@Mishiranu No, you don't have to. Either you wait until a volunteer does it for you or you automate it yourself since I guess that all of those modules are similar. See https://f-droid.org/manual/html_node/Metadata.html and https://gitlab.com/fdroid/fdroiddata/tree/master/metadata for examples (they accept pull requests).

**Comment by Mishiranu** [comment]
@jiyagaimo I didn't know about this. If I can just add a new metadata file and make a PR, it makes all much easier. So OK, I'll look at this when I get time.

**Comment by dimqua** [comment]
https://gitlab.com/fdroid/rfp/issues/164

I think it's fine to include only the app and webm libraries (without modules). And keep the auto updater where it is.

**Comment by Mishiranu** [comment]
Well, that's great. But I'd like to add extensions too. In previous update I've added some features to manage extensions from different sources planning to add them all to fdroid.

Right now I'd like to fix some issues and release a new version of client before releasing it to froid.

**Comment by Mishiranu** [comment]
Also Dashchan uses some external APIs which requires API keys. They are specified during compile time and taken from `private.properties`. This file is not on my repo because it's not a good practice to post them publically.

Is it possible to include them in froid somehow? They are not so important but bring some features.

**Comment by KOLANICH** [comment]
>This file is not on my repo because it's not a good practice to post them publically.

I guess it'd be better to allow the users to (possibly after obtaining in an automated way) provide own keys in the settings.

**Comment by Mishiranu** [comment]
I think I can use advanced preferences (see wiki) for keys. In this case user can add his keys and app will use them. It's a good idea.

**Comment by Mishiranu** [comment]
I'll probably try to release the application to F-Droid myself later since I want to try to use reproducible builds. I already implemented tagging, so I'm waiting until v2 signing will work for reproducible builds (I don't want to publish releases with v1 scheme only). Okay?

**Comment by Mishiranu** [comment]
MR is created. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7807

**Comment by IzzySoft** [comment]
You are going for reproducible builds (as you have defined "binaries")? Further: your Fastlane lacks `en-US`, which is used as default locale and hence mandatory (yes I know, Americans… but nothing I could do about that). `ru` is fine, no need to change that (unless you plan for Google Play).

**Comment by Mishiranu** [comment]
> You are going for reproducible builds

Right.

> your Fastlane lacks `en-US`

Hm. I thought "en" is enough, I even checked existing index for this locale, and it seems some applications use just "en" in metadata instead of "en-US". Is "en-US" required by F-Droid parser instead of "en"? I can change that.

> ru is fine, no need to change that

According to fastlane doc, "ru" is a proper locale. "ru" is also used much more often than "ru-RU" in metadata, so I suppose it's correct to use "ru".

**Comment by Mishiranu** [comment]
Ok, changed "en" to "en-US". Actually, I rebased the repo, but that's fine :eyes: .

**Comment by IzzySoft** [comment]
Yes, `en-US` is required by F-Droid (don't listen if someone tries convincing you otherwise – I know what I'm talking about; saw fails often enough, always the same cause). Google would even require **ALL** your locales using `xx-YY` (so no idea what someone with `de-AT` would get if only `de-DE` and `en-US` were present)…

Thanks for adjusting! Did you make sure the change is covered by a tag (i.e. there was a tag created pointing to a commit that includes the change)? And good luck then with reproducible builds! That's the supreme discipline, and sometimes not that easy to achieve. :crossed_fingers:

**Comment by Mishiranu** [comment]
> Did you make sure the change is covered by a tag

Yes, I re-pointed the tag on new "Release 3.1.2" commit, though the release APK is the same (source code didn't change, only directory in metadata was renamed).

> And good luck then with reproducible builds! That's the supreme discipline, and sometimes not that easy to achieve. crossed_fingers

Thanks! Yes, I know it's not easy. F-Droid doc is very helpful on this.

**Comment by Mishiranu** [comment]
The client is available in F-Droid now!

https://f-droid.org/packages/com.mishiranu.dashchan/

Actually, the link doesn't work in web version now, seems like the website wasn't updated, but it's accessible from F-Droid client.

Thanks for waiting this long.

**Comment by KOLANICH** [comment]
Thank you.

**Comment by IzzySoft** [comment]
Website's updated asynchronously, usually takes a day or so to reflect the changes.

**Comment by Mishiranu** [comment]
I see. It's not a big deal, though.
