### ISSUE TITLE
endchan error

### ISSUE THREAD

**Issue by doonoo** [Mishiranu/Dashchan#144]
![screenshot_20170615-004639](https://user-images.githubusercontent.com/18385494/27165777-d2b0102a-5185-11e7-904c-06877e38bc8f.png)

Clicking the post number puts you to a different thread rather then the post itself.

**Comment by Mishiranu** [comment]
Because they break their links. For example, old links:
`/operate/res/1017.html#1018` — 1018 post in 1017 thread, everything is clear.
And new links:
`/operate/res/6460.html#6460` — 6460 post in 6460… no, in the same 1017 thread!

I can add a temporal fix for this but it definitely should be fixed on the server side.

**Comment by Mishiranu** [comment]
Fixed.
