### ISSUE TITLE
HTTP cache missing

### ISSUE THREAD

**Issue by kellerbernd** [Mishiranu/Dashchan#228]
I updated a Dashchan extension to support LynxChan. Doing that, I found out that some features, e.g. watching a thread's post count, don't work properly:
* client makes a request to read /foo/res/2342.json to display a thread
* user watches thread
* client makes repeated request to read the post count, which result in the same request to fetch /foo/res/2342,json
* server returns 304: not modified
* client extension throws this error up the chain, Dashchan is confused because it doesn't know the post count and displays "-1" in the UI instead.

Proposed solution (would help to implement it):
Use HttpResponseCache in DashChan's HTTP abstraction to cache results, so that repeated requests to the same resource still return the proper data.

**Comment by Mishiranu** [comment]
I don't think it's necessary to implement cache, as it will be needed to store responses somewhere. Instead, Dashchan caches the objects received from extension. I actually don't understand how it's possible, 304 is returned only when you pass a proper HttpValidator (which provides If-Modified-Since and If-None-Match headers), and threads watcher and posts page use different HttpValidator objects, so these entities shouldn't cross.

I'm planning to merge threads watcher with the data source for posts page, so this particular problem won't exist. Implementing an additional HTTP cache is definitely overkill.
