### ISSUE TITLE
Can't read long filenames

### ISSUE THREAD

**Issue by iiiGerardoiii** [Mishiranu/Dashchan#61]
![2016-06-16 05 52 03](https://cloud.githubusercontent.com/assets/6264194/16860141/cf35f222-49fa-11e6-9fa0-0a70ed2b162a.png)

There's times you find images or webms with long filenames, specially on filename threads. I can't find a way to read the whole filename except by downloading the file and see it on a file browser.

**Comment by GiRaFa-SM** [comment]
Yeah, maybe a small font probably will solve this problem . To be honest a bigger pop up for showing the complete name doesn't look good.

**Comment by Mishiranu** [comment]
I think it's not a big problem because in most cases you should see the full name. There are a lot of restrictions regards to long names such as max length of poster name of max length of user icon title, but I can't take into account all these things.

The system dialog's title is limited to 2 lines. I can try to add a couple of lines, but there will be cases when even this won't help.

**Comment by Mishiranu** [comment]
Now dialog title is limited to 4 lines. 7c2d48ae9ea00462400c254e9289b1f19a5bc735
