### ISSUE TITLE
Some images or videos won't load (8chan)

### ISSUE THREAD

**Issue by diyasteng** [Mishiranu/Dashchan#91]
Some images / videos from 8ch wont load and shows a 404 message. Tried /pol/, /tech,/ /v/ so it pretty much happens to every board.

This started the other day.

**Comment by Mishiranu** [comment]
Fixed.

**Comment by diyasteng** [comment]
the bug still happens on the latest update.

**Comment by Mishiranu** [comment]
Works for me.
For Tor users it's not fixable, but on regular 8ch it should work. Are you sure you have the latest client and extension?
Try to open thumbnails in regular browser, but replace thumbnails domain with "media.8ch.net" (instead of "media2.8ch.net").
Some images also can be without thumbnail because they are marked as spoiler.
